"""
Shared fixtures for LXMF interop tests (C++ <-> Python).

Loads test vectors from:
  /tmp/lxmf_cpp_vectors.json    - generated by C++ testCppGenerateVectors()
  /tmp/lxmf_test_vectors_full.json - generated by generate_vectors.py
"""

import json
import pytest
import RNS


@pytest.fixture(scope="session")
def cpp_vectors():
    """Load C++ generated test vectors."""
    path = "/tmp/lxmf_cpp_vectors.json"
    try:
        with open(path) as f:
            return json.load(f)
    except FileNotFoundError:
        pytest.skip(f"C++ vectors not found at {path}. Run: pio test -e native17 -f test_lxmf")


@pytest.fixture(scope="session")
def python_vectors():
    """Load Python generated test vectors."""
    path = "/tmp/lxmf_test_vectors_full.json"
    try:
        with open(path) as f:
            return json.load(f)
    except FileNotFoundError:
        pytest.skip(f"Python vectors not found at {path}. Run: python3 generate_vectors.py")


def get_vector_by_name(vectors, name):
    """Find a vector by name in a vector list."""
    for v in vectors:
        if v["name"] == name:
            return v
    pytest.fail(f"Vector '{name}' not found in vectors")


def identity_from_pub_hex(pub_hex):
    """Reconstruct an RNS Identity from a hex-encoded public key."""
    pub_bytes = bytes.fromhex(pub_hex)
    identity = RNS.Identity(create_keys=False)
    identity.load_public_key(pub_bytes)
    return identity
