"""
LXMF interop tests: validate C++ output in Python.

Reads /tmp/lxmf_cpp_vectors.json (generated by C++ testCppGenerateVectors)
and verifies that Python LXMF can correctly unpack and validate the messages.

Also tests bidirectional roundtrip: Python → C++ → Python.
"""

import hashlib
import json
import pytest

import RNS
import LXMF
from RNS.vendor import umsgpack

from conftest import get_vector_by_name, identity_from_pub_hex


def register_source_identity(vector):
    """Register source identity so Python LXMF can validate signatures."""
    source_identity = identity_from_pub_hex(vector["source_identity_pub"])
    source_hash = bytes.fromhex(vector["source_hash"])
    RNS.Identity.remember(None, source_hash, source_identity.get_public_key())
    return source_identity


def validate_signature_manual(packed_bytes, pub_hex):
    """Manually validate Ed25519 signature on packed LXMF message."""
    identity = identity_from_pub_hex(pub_hex)

    dest_hash = packed_bytes[:16]
    src_hash = packed_bytes[16:32]
    signature = packed_bytes[32:96]
    payload = packed_bytes[96:]

    # Hash and signature are computed over the payload WITHOUT stamp
    decoded = umsgpack.unpackb(payload)
    if len(decoded) > 4:
        # Strip stamp, repack
        payload = umsgpack.packb(decoded[:4])

    hashed_part = dest_hash + src_hash + payload
    msg_hash = hashlib.sha256(hashed_part).digest()
    signed_part = hashed_part + msg_hash

    return identity.validate(signature, signed_part)


# ==================== C++ → Python Tests ====================


class TestCppBasicUnpack:
    """Test that Python can unpack basic C++ messages."""

    def test_content_and_title(self, cpp_vectors):
        v = get_vector_by_name(cpp_vectors, "cpp_basic")
        register_source_identity(v)

        packed = bytes.fromhex(v["packed"])
        msg = LXMF.LXMessage.unpack_from_bytes(packed)

        assert msg.content_as_string() == v["content"]
        assert msg.title_as_string() == v["title"]

    def test_empty_content(self, cpp_vectors):
        v = get_vector_by_name(cpp_vectors, "cpp_empty")
        register_source_identity(v)

        packed = bytes.fromhex(v["packed"])
        msg = LXMF.LXMessage.unpack_from_bytes(packed)

        assert msg.content_as_string() == ""
        assert msg.title_as_string() == ""

    def test_unicode_content(self, cpp_vectors):
        v = get_vector_by_name(cpp_vectors, "cpp_unicode")
        register_source_identity(v)

        packed = bytes.fromhex(v["packed"])
        msg = LXMF.LXMessage.unpack_from_bytes(packed)

        assert msg.content_as_string() == v["content"]
        assert msg.title_as_string() == v["title"]


class TestCppSignatureValid:
    """Test that C++ Ed25519 signatures are valid."""

    def test_basic_signature(self, cpp_vectors):
        v = get_vector_by_name(cpp_vectors, "cpp_basic")
        packed = bytes.fromhex(v["packed"])
        assert validate_signature_manual(packed, v["source_identity_pub"])

    def test_empty_signature(self, cpp_vectors):
        v = get_vector_by_name(cpp_vectors, "cpp_empty")
        packed = bytes.fromhex(v["packed"])
        assert validate_signature_manual(packed, v["source_identity_pub"])

    def test_fields_signature(self, cpp_vectors):
        v = get_vector_by_name(cpp_vectors, "cpp_with_fields")
        packed = bytes.fromhex(v["packed"])
        assert validate_signature_manual(packed, v["source_identity_pub"])

    def test_unicode_signature(self, cpp_vectors):
        v = get_vector_by_name(cpp_vectors, "cpp_unicode")
        packed = bytes.fromhex(v["packed"])
        assert validate_signature_manual(packed, v["source_identity_pub"])


class TestCppHashMatches:
    """Test that Python-computed hash matches C++ reported hash."""

    def _verify_hash(self, vector):
        packed = bytes.fromhex(vector["packed"])
        dest_hash = packed[:16]
        src_hash = packed[16:32]
        payload = packed[96:]

        hashed_part = dest_hash + src_hash + payload
        computed_hash = hashlib.sha256(hashed_part).digest()

        assert computed_hash.hex() == vector["message_hash"]

    def test_basic_hash(self, cpp_vectors):
        self._verify_hash(get_vector_by_name(cpp_vectors, "cpp_basic"))

    def test_empty_hash(self, cpp_vectors):
        self._verify_hash(get_vector_by_name(cpp_vectors, "cpp_empty"))

    def test_fields_hash(self, cpp_vectors):
        self._verify_hash(get_vector_by_name(cpp_vectors, "cpp_with_fields"))

    def test_unicode_hash(self, cpp_vectors):
        self._verify_hash(get_vector_by_name(cpp_vectors, "cpp_unicode"))


class TestCppFields:
    """Test that C++ field encoding can be decoded by Python."""

    def test_fields_present(self, cpp_vectors):
        v = get_vector_by_name(cpp_vectors, "cpp_with_fields")
        register_source_identity(v)

        packed = bytes.fromhex(v["packed"])
        msg = LXMF.LXMessage.unpack_from_bytes(packed)

        # C++ uses binary keys (Bytes), Python LXMF unpacks them as bytes
        fields = msg.get_fields()
        assert fields is not None
        assert len(fields) == v["fields_count"]

    def test_field_values(self, cpp_vectors):
        v = get_vector_by_name(cpp_vectors, "cpp_with_fields")
        register_source_identity(v)

        packed = bytes.fromhex(v["packed"])
        msg = LXMF.LXMessage.unpack_from_bytes(packed)
        fields = msg.get_fields()

        # Check each field from the vector
        for key_hex, val_hex in v["fields"].items():
            key_bytes = bytes.fromhex(key_hex)
            val_bytes = bytes.fromhex(val_hex)
            assert key_bytes in fields, f"Field key {key_hex} not found in unpacked fields"
            assert fields[key_bytes] == val_bytes, f"Field value mismatch for key {key_hex}"


class TestCppStamp:
    """Test that C++ generated stamps are valid per Python LXMF."""

    def test_stamp_present(self, cpp_vectors):
        """C++ stamped message should have a 32-byte stamp after unpack."""
        v = get_vector_by_name(cpp_vectors, "cpp_with_stamp")
        register_source_identity(v)

        packed = bytes.fromhex(v["packed"])
        msg = LXMF.LXMessage.unpack_from_bytes(packed)

        assert msg.stamp is not None, "Stamp missing from unpacked message"
        assert len(msg.stamp) == 32, f"Stamp wrong size: {len(msg.stamp)}"

    def test_stamp_bytes_match(self, cpp_vectors):
        """Stamp bytes from unpack should match what C++ reported."""
        v = get_vector_by_name(cpp_vectors, "cpp_with_stamp")
        register_source_identity(v)

        packed = bytes.fromhex(v["packed"])
        msg = LXMF.LXMessage.unpack_from_bytes(packed)

        expected_stamp = bytes.fromhex(v["stamp"])
        assert msg.stamp == expected_stamp

    def test_stamp_validates(self, cpp_vectors):
        """Python LXStamper should accept the C++ generated stamp."""
        from LXMF import LXStamper

        v = get_vector_by_name(cpp_vectors, "cpp_with_stamp")
        register_source_identity(v)

        packed = bytes.fromhex(v["packed"])
        msg = LXMF.LXMessage.unpack_from_bytes(packed)

        stamp_cost = v["stamp_cost"]
        assert msg.validate_stamp(stamp_cost), (
            f"Python rejected C++ stamp (cost={stamp_cost})"
        )

    def test_stamp_signature_valid(self, cpp_vectors):
        """Signature should be valid (computed over 4-element payload without stamp)."""
        v = get_vector_by_name(cpp_vectors, "cpp_with_stamp")
        packed = bytes.fromhex(v["packed"])
        assert validate_signature_manual(packed, v["source_identity_pub"])

    def test_stamp_hash_matches(self, cpp_vectors):
        """Hash should be computed over the payload WITHOUT stamp."""
        v = get_vector_by_name(cpp_vectors, "cpp_with_stamp")
        packed = bytes.fromhex(v["packed"])

        dest_hash = packed[:16]
        src_hash = packed[16:32]
        payload = packed[96:]

        # Strip stamp (5th element) before computing hash
        decoded = umsgpack.unpackb(payload)
        if len(decoded) > 4:
            payload = umsgpack.packb(decoded[:4])

        hashed_part = dest_hash + src_hash + payload
        computed_hash = hashlib.sha256(hashed_part).digest()
        assert computed_hash.hex() == v["message_hash"]


class TestBidirectionalRoundtrip:
    """Test that Python→C++→Python roundtrip preserves data.

    Python generates vectors, C++ unpacks and repacks them (testCppGenerateVectors),
    then Python unpacks the C++ output. We verify the original Python vectors
    match the C++ output.
    """

    def test_basic_roundtrip_hash(self, python_vectors, cpp_vectors):
        """Verify hash computation is consistent across implementations.

        Note: hash won't be identical because C++ generates new messages
        (different keys/timestamps). Instead we verify that Python can
        independently compute the same hash from the C++ packed bytes.
        Hash is always over the 4-element payload (without stamp).
        """
        for v in cpp_vectors:
            packed = bytes.fromhex(v["packed"])
            dest_hash = packed[:16]
            src_hash = packed[16:32]
            payload = packed[96:]

            # Strip stamp (5th element) if present before computing hash
            decoded = umsgpack.unpackb(payload)
            if len(decoded) > 4:
                payload = umsgpack.packb(decoded[:4])

            hashed_part = dest_hash + src_hash + payload
            py_hash = hashlib.sha256(hashed_part).digest()

            assert py_hash.hex() == v["message_hash"], (
                f"Hash mismatch for {v['name']}: "
                f"Python={py_hash.hex()}, C++={v['message_hash']}"
            )

    def test_all_cpp_vectors_unpack(self, cpp_vectors):
        """Every C++ vector should unpack without error in Python."""
        for v in cpp_vectors:
            register_source_identity(v)
            packed = bytes.fromhex(v["packed"])
            msg = LXMF.LXMessage.unpack_from_bytes(packed)

            assert msg.content_as_string() == v["content"], (
                f"Content mismatch for {v['name']}"
            )
            assert msg.title_as_string() == v["title"], (
                f"Title mismatch for {v['name']}"
            )

    def test_all_cpp_signatures_valid(self, cpp_vectors):
        """Every C++ vector should have a valid signature."""
        for v in cpp_vectors:
            packed = bytes.fromhex(v["packed"])
            assert validate_signature_manual(packed, v["source_identity_pub"]), (
                f"Signature invalid for {v['name']}"
            )
